---
# This workflow runs the calling workflow from the main branch
# in this repository for testing purposes.
name: (main) Run collection certification checks

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

concurrency:
  group: cert-ver-main-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Test with the default ansible-core version (currently 2.16.0).
  # Sanity tests automatically run against stable-2.16, 2.18, and 2.20.
  call-default:
    uses: ./.github/workflows/certification-reusable.yml

  # Test build-import and lint with ansible-core 2.18.x
  call-2-18:
    uses: ./.github/workflows/certification-reusable.yml
    with:
      ansible-core-version: '2.18.0'

  # Test build-import and lint with ansible-core 2.20.x
  call-2-20:
    uses: ./.github/workflows/certification-reusable.yml
    with:
      ansible-core-version: '2.20.0'

  # Test when the collection root is not at the root of the repository
  call-collection-root:
    uses: ./.github/workflows/certification-reusable.yml
    with:
      collection-root: "tests/fixtures/collection"
